# Eat Safe, Love

## Notebook Set Up

In [1]:
from pymongo import MongoClient
import pandas as pd
from pprint import pprint

In [2]:
# Create an instance of MongoClient
mongo = MongoClient(port=27017)

In [3]:
# assign the uk_food database to a variable name
db = mongo['uk_food']

In [5]:
# review the collections in our database
db.list_collection_names()

['establishments']

In [7]:
# assign the collection to a variable
establishments = db['establishments']

In [28]:
establishments.find_one()

{'_id': ObjectId('6643e432fc3e28490008fd85'),
 'FHRSID': 1043695,
 'ChangesByServerID': 0,
 'LocalAuthorityBusinessID': 'PI/000073616',
 'BusinessName': 'The Pavilion',
 'BusinessType': 'Restaurant/Cafe/Canteen',
 'BusinessTypeID': 1,
 'AddressLine1': 'East Cliff Pavilion',
 'AddressLine2': 'Wear Bay Road',
 'AddressLine3': 'Folkestone',
 'AddressLine4': 'Kent',
 'PostCode': 'CT19 6BL',
 'Phone': '',
 'RatingValue': 5,
 'RatingKey': 'fhrs_5_en-gb',
 'RatingDate': '2018-04-04T00:00:00',
 'LocalAuthorityCode': '188',
 'LocalAuthorityName': 'Folkestone and Hythe',
 'LocalAuthorityWebSite': 'http://www.folkestone-hythe.gov.uk',
 'LocalAuthorityEmailAddress': 'foodteam@folkestone-hythe.gov.uk',
 'scores': {'Hygiene': 5, 'Structural': 5, 'ConfidenceInManagement': 5},
 'SchemeType': 'FHRS',
 'geocode': {'longitude': 1.195625, 'latitude': 51.083812},
 'RightToReply': '',
 'Distance': 4591.765489457773,
 'NewRatingPending': False,
 'meta': {'dataSource': None,
  'extractDate': '0001-01-01T00:00:00',
  'itemCount': 0,
  'returncode': None,
  'totalCount': 0,
  'totalPages': 0,
  'pageSize': 0,
  'pageNumber': 0},
 'links': [{'rel': 'self',
   'href': 'https://api.ratings.food.gov.uk/establishments/1043695'}]}

## Part 3: Exploratory Analysis
Unless otherwise stated, for each question: 
* Use `count_documents` to display the number of documents contained in the result.
* Display the first document in the results using `pprint`.
* Convert the result to a Pandas DataFrame, print the number of rows in the DataFrame, and display the first 10 rows.

### 1. Which establishments have a hygiene score equal to 20?

In [14]:
# Find the establishments with a hygiene score of 20
query = {'scores.Hygiene': 20}
results = list(establishments.find(query))

# Use count_documents to display the number of documents in the result
print(f'Number of documents in the result: {establishments.count_documents(query)}')
# Display the first document in the results using pprint
pprint(results[0])

Number of documents in the result: 41
{'AddressLine1': '5-6 Southfields Road',
 'AddressLine2': 'Eastbourne',
 'AddressLine3': 'East Sussex',
 'AddressLine4': '',
 'BusinessName': 'The Chase Rest Home',
 'BusinessType': 'Caring Premises',
 'BusinessTypeID': 5,
 'ChangesByServerID': 0,
 'Distance': 4613.888288172291,
 'FHRSID': 110681,
 'LocalAuthorityBusinessID': '4029',
 'LocalAuthorityCode': '102',
 'LocalAuthorityEmailAddress': 'Customerfirst@eastbourne.gov.uk',
 'LocalAuthorityName': 'Eastbourne',
 'LocalAuthorityWebSite': 'http://www.eastbourne.gov.uk/foodratings',
 'NewRatingPending': False,
 'Phone': '',
 'PostCode': 'BN21 1BU',
 'RatingDate': '2021-09-23T00:00:00',
 'RatingKey': 'fhrs_0_en-gb',
 'RatingValue': 0,
 'RightToReply': '',
 'SchemeType': 'FHRS',
 '_id': ObjectId('6643e432fc3e2849000918b9'),
 'geocode': {'latitude': 50.769705, 'longitude': 0.27694},
 'links': [{'href': 'https://api.ratings.food.gov.uk/establishments/110681',
            'rel': 'self'}],
 'meta': {'dataSource': None,
          'extractDate': '0001-01-01T00:00:00',
          'itemCount': 0,
          'pageNumber': 0,
          'pageSize': 0,
          'returncode': None,
          'totalCount': 0,
          'totalPages': 0},
 'scores': {'ConfidenceInManagement': 20, 'Hygiene': 20, 'Structural': 20}}

In [25]:
# Convert the result to a Pandas DataFrame
hygiene_df = pd.json_normalize(results)
# Display the number of rows in the DataFrame
print(f'Number of rows in the DataFrame: {hygiene_df["_id"].count()}')
# Display the first 10 rows of the DataFrame
hygiene_df.head(10)

Number of rows in the DataFrame: 41

,_id,FHRSID,ChangesByServerID,LocalAuthorityBusinessID,BusinessName,BusinessType,BusinessTypeID,AddressLine1,AddressLine2,AddressLine3,...,geocode.longitude,geocode.latitude,meta.dataSource,meta.extractDate,meta.itemCount,meta.returncode,meta.totalCount,meta.totalPages,meta.pageSize,meta.pageNumber
0,6643e432fc3e2849000918b9,110681,0,4029,The Chase Rest Home,Caring Premises,5,5-6 Southfields Road,Eastbourne,East Sussex,...,0.276940,50.769705,None,0001-01-01T00:00:00,0,None,0,0,0,0
1,6643e432fc3e284900091c37,612039,0,1970/FOOD,Brenalwood,Caring Premises,5,Hall Lane,Walton-on-the-Naze,Essex,...,1.278721,51.857536,None,0001-01-01T00:00:00,0,None,0,0,0,0
2,6643e432fc3e284900091f42,730933,0,1698/FOOD,Melrose Hotel,Hotel/bed & breakfast/guest house,7842,53 Marine Parade East,Clacton On Sea,Essex,...,1.159270,51.789429,None,0001-01-01T00:00:00,0,None,0,0,0,0
3,6643e432fc3e28490009213e,172735,0,PI/000023858,Seaford Pizza,Takeaway/sandwich shop,7844,4 High Street,Seaford,East Sussex,...,0.102020,50.770885,None,0001-01-01T00:00:00,0,None,0,0,0,0
4,6643e432fc3e284900092140,172953,0,PI/000024532,Golden Palace,Restaurant/Cafe/Canteen,1,5 South Street,Seaford,East Sussex,...,0.101446,50.770724,None,0001-01-01T00:00:00,0,None,0,0,0,0
5,6643e432fc3e284900092ae0,512854,0,12/00816/BUTH,Ashby's Butchers,Retailers - other,4613,777 Southchurch Road,Southend-On-Sea,Essex,...,0.736349,51.541448,None,0001-01-01T00:00:00,0,None,0,0,0,0
6,6643e432fc3e284900092cff,1537089,0,22/00224/RESTUN,South Sea Express Cuisine,Restaurant/Cafe/Canteen,1,33 Alexandra Street,Southend-on-sea,Essex,...,0.712167,51.535007,None,0001-01-01T00:00:00,0,None,0,0,0,0
7,6643e433fc3e28490009422c,155648,0,EH/00006058,Golden Palace,Takeaway/sandwich shop,7844,7 London Road,Rayleigh,Essex,...,0.602364,51.591515,None,0001-01-01T00:00:00,0,None,0,0,0,0
8,6643e433fc3e28490009466e,1012883,0,17/00110/MIXED/S,The Tulip Tree,Restaurant/Cafe/Canteen,1,3 The Village,Chiddingstone,KENT,...,0.146450,51.185947,None,0001-01-01T00:00:00,0,None,0,0,0,0
9,6643e433fc3e284900094e8c,644109,0,41811,F & S,Retailers - other,4613,,81 Southernhay,Basildon,...,0.462307,51.570050,None,0001-01-01T00:00:00,0,None,0,0,0,0

### 2. Which establishments in London have a `RatingValue` greater than or equal to 4?

In [34]:
# Find the establishments with London as the Local Authority and has a RatingValue greater than or equal to 4.
query = {'AddressLine3': "London", 'RatingValue': {'$gte': 4}}
results = list(establishments.find(query))

# Use count_documents to display the number of documents in the result
print(f'Number of documents in the result: {establishments.count_documents(query)}')
# Display the first document in the results using pprint
pprint(results[0])

Number of documents in the result: 1004
{'AddressLine1': '101A Woolwich Road',
 'AddressLine2': 'Abbey Wood',
 'AddressLine3': 'London',
 'AddressLine4': '',
 'BusinessName': 'Belvedere Sports & Social Club',
 'BusinessType': 'Pub/bar/nightclub',
 'BusinessTypeID': 7843,
 'ChangesByServerID': 0,
 'Distance': 4645.185370358264,
 'FHRSID': 329114,
 'LocalAuthorityBusinessID': '03260/2001/2/000',
 'LocalAuthorityCode': '503',
 'LocalAuthorityEmailAddress': 'food.safety@bexley.gov.uk',
 'LocalAuthorityName': 'Bexley',
 'LocalAuthorityWebSite': 'http://www.bexley.gov.uk',
 'NewRatingPending': False,
 'Phone': '',
 'PostCode': 'SE2 0DY',
 'RatingDate': '2019-01-10T00:00:00',
 'RatingKey': 'fhrs_4_en-gb',
 'RatingValue': 4,
 'RightToReply': '',
 'SchemeType': 'FHRS',
 '_id': ObjectId('6643e433fc3e284900096890'),
 'geocode': {'latitude': 51.482981, 'longitude': 0.136518},
 'links': [{'href': 'http://api.ratings.food.gov.uk/establishments/329114',
            'rel': 'self'}],
 'meta': {'dataSource': None,
          'extractDate': '0001-01-01T00:00:00',
          'itemCount': 0,
          'pageNumber': 0,
          'pageSize': 0,
          'returncode': None,
          'totalCount': 0,
          'totalPages': 0},
 'scores': {'ConfidenceInManagement': 10, 'Hygiene': 5, 'Structural': 5}}

In [35]:
# Convert the result to a Pandas DataFrame
london_df = pd.json_normalize(results)
# Display the number of rows in the DataFrame
print(f'Number of rows in the DataFrame: {london_df["_id"].count()}')
# Display the first 10 rows of the DataFrame
london_df.head(10)

Number of rows in the DataFrame: 1004

,_id,FHRSID,ChangesByServerID,LocalAuthorityBusinessID,BusinessName,BusinessType,BusinessTypeID,AddressLine1,AddressLine2,AddressLine3,...,geocode.longitude,geocode.latitude,meta.dataSource,meta.extractDate,meta.itemCount,meta.returncode,meta.totalCount,meta.totalPages,meta.pageSize,meta.pageNumber
0,6643e433fc3e284900096890,329114,0,03260/2001/2/000,Belvedere Sports & Social Club,Pub/bar/nightclub,7843,101A Woolwich Road,Abbey Wood,London,...,0.136518,51.482981,None,0001-01-01T00:00:00,0,None,0,0,0,0
1,6643e433fc3e284900096891,329113,0,03260/0075/0/000,The Croft Day Nursery,Caring Premises,5,75 Woolwich Road,Abbey Wood,London,...,0.136519,51.482981,None,0001-01-01T00:00:00,0,None,0,0,0,0
2,6643e433fc3e2849000969f0,1402880,0,21/00281/CP,Independent Catering Management At Dulverton P...,School/college/university,7845,Dulverton School,Dulverton Road,London,...,0.080990,51.435490,None,0001-01-01T00:00:00,0,None,0,0,0,0
3,6643e433fc3e284900096a99,975472,0,17/00162/CP,Abbey Good Coffee,Restaurant/Cafe/Canteen,1,Lesnes Abbey Lodge,New Road,London,...,0.120352,51.479427,None,0001-01-01T00:00:00,0,None,0,0,0,0
4,6643e433fc3e284900096a9a,1262185,0,20/00155/CP,Chestnuts Kiosk Limited,Restaurant/Cafe/Canteen,1,Lesnes Abbey Lodge,New Road,London,...,0.120352,51.479427,None,0001-01-01T00:00:00,0,None,0,0,0,0
5,6643e433fc3e284900096c04,687040,0,03190/0014/0/000,Brownes Chemist,Retailers - other,4613,14-16 Wilton Road,Abbey Wood,London,...,0.121521,51.490340,None,0001-01-01T00:00:00,0,None,0,0,0,0
6,6643e433fc3e284900096c1c,610394,0,03190/0008/0/000,A W Foodhall,Retailers - other,4613,8 Wilton Road,Abbey Wood,London,...,0.121087,51.490312,None,0001-01-01T00:00:00,0,None,0,0,0,0
7,6643e433fc3e284900096c76,1109051,0,19/00026/CP,BP Thamesmead Service Station,Retailers - other,4613,Service Station,Harrow Manorway,London,...,0.121431,51.493362,None,0001-01-01T00:00:00,0,None,0,0,0,0
8,6643e433fc3e284900096c99,1385124,0,14474,Alexander McLeod Primary School,School/college/university,7845,Fuchsia Street,,London,...,0.113690,51.486450,None,0001-01-01T00:00:00,0,None,0,0,0,0
9,6643e433fc3e284900096d39,1256695,0,20/00134/CP,Lakeside Nursery,Caring Premises,5,Lakeside Complex,2 Bazalgette Way,London,...,0.124091,51.501067,None,0001-01-01T00:00:00,0,None,0,0,0,0

### 3. What are the top 5 establishments with a `RatingValue` rating value of 5, sorted by lowest hygiene score, nearest to the new restaurant added, "Penang Flavours"?

In [66]:
# Search within 0.01 degree on either side of the latitude and longitude.
# Rating value must equal 5
# Sort by hygiene score

degree_search = 0.01
latitude = 51.49014200
longitude = 0.08384000

north_bound = latitude + degree_search
south_bound = latitude - degree_search
east_bound = longitude + degree_search
west_bound = longitude - degree_search


query = {'scores.Hygiene': {'$ne': None},
        'geocode.latitude': {'$lte': north_bound, '$gte': south_bound},
        'geocode.longitude': {'$lte': east_bound, '$gte': west_bound},
                              'RatingValue': 5
        }
sort = [('scores.Hygiene', 1)]
limit = 5     
         
results = list(establishments.find(query).sort(sort).limit(limit))

# Print the results
pprint(results)

[{'AddressLine1': 'Restaurant And Premises 107A Plumstead High Street',
  'AddressLine2': '',
  'AddressLine3': 'Plumstead',
  'AddressLine4': 'Greenwich',
  'BusinessName': 'Howe and Co Fish and Chips - Van 17',
  'BusinessType': 'Mobile caterer',
  'BusinessTypeID': 7846,
  'ChangesByServerID': 0,
  'Distance': 4646.95593107927,
  'FHRSID': 1380578,
  'LocalAuthorityBusinessID': '14425',
  'LocalAuthorityCode': '511',
  'LocalAuthorityEmailAddress': 'health@royalgreenwich.gov.uk',
  'LocalAuthorityName': 'Greenwich',
  'LocalAuthorityWebSite': 'http://www.royalgreenwich.gov.uk',
  'NewRatingPending': False,
  'Phone': '',
  'PostCode': 'SE18 1SE',
  'RatingDate': '2021-11-11T00:00:00',
  'RatingKey': 'fhrs_5_en-gb',
  'RatingValue': 5,
  'RightToReply': '',
  'SchemeType': 'FHRS',
  '_id': ObjectId('6643e433fc3e2849000970f6'),
  'geocode': {'latitude': 51.4875335693359, 'longitude': 0.0925370007753372},
  'links': [{'href': 'http://api.ratings.food.gov.uk/establishments/1380578',
             'rel': 'self'}],
  'meta': {'dataSource': None,
           'extractDate': '0001-01-01T00:00:00',
           'itemCount': 0,
           'pageNumber': 0,
           'pageSize': 0,
           'returncode': None,
           'totalCount': 0,
           'totalPages': 0},
  'scores': {'ConfidenceInManagement': 0, 'Hygiene': 0, 'Structural': 0}},
 {'AddressLine1': '35 Lakedale Road',
  'AddressLine2': '',
  'AddressLine3': 'Plumstead',
  'AddressLine4': 'Greenwich',
  'BusinessName': 'Atlantic Fish Bar',
  'BusinessType': 'Takeaway/sandwich shop',
  'BusinessTypeID': 7844,
  'ChangesByServerID': 0,
  'Distance': 4646.974611855838,
  'FHRSID': 694478,
  'LocalAuthorityBusinessID': 'PI/000086506',
  'LocalAuthorityCode': '511',
  'LocalAuthorityEmailAddress': 'health@royalgreenwich.gov.uk',
  'LocalAuthorityName': 'Greenwich',
  'LocalAuthorityWebSite': 'http://www.royalgreenwich.gov.uk',
  'NewRatingPending': False,
  'Phone': '',
  'PostCode': 'SE18 1PR',
  'RatingDate': '2021-06-16T00:00:00',
  'RatingKey': 'fhrs_5_en-gb',
  'RatingValue': 5,
  'RightToReply': '',
  'SchemeType': 'FHRS',
  '_id': ObjectId('6643e433fc3e284900097134'),
  'geocode': {'latitude': 51.4867296, 'longitude': 0.0912164},
  'links': [{'href': 'http://api.ratings.food.gov.uk/establishments/694478',
             'rel': 'self'}],
  'meta': {'dataSource': None,
           'extractDate': '0001-01-01T00:00:00',
           'itemCount': 0,
           'pageNumber': 0,
           'pageSize': 0,
           'returncode': None,
           'totalCount': 0,
           'totalPages': 0},
  'scores': {'ConfidenceInManagement': 5, 'Hygiene': 0, 'Structural': 0}},
 {'AddressLine1': 'Plumstead Manor School Old Mill Road',
  'AddressLine2': '',
  'AddressLine3': 'Plumstead',
  'AddressLine4': 'Greenwich',
  'BusinessName': 'Plumstead Manor Nursery',
  'BusinessType': 'Caring Premises',
  'BusinessTypeID': 5,
  'ChangesByServerID': 0,
  'Distance': 4646.9740101340385,
  'FHRSID': 695241,
  'LocalAuthorityBusinessID': 'PI/000179088',
  'LocalAuthorityCode': '511',
  'LocalAuthorityEmailAddress': 'health@royalgreenwich.gov.uk',
  'LocalAuthorityName': 'Greenwich',
  'LocalAuthorityWebSite': 'http://www.royalgreenwich.gov.uk',
  'NewRatingPending': False,
  'Phone': '',
  'PostCode': 'SE18 1QG',
  'RatingDate': '2021-06-16T00:00:00',
  'RatingKey': 'fhrs_5_en-gb',
  'RatingValue': 5,
  'RightToReply': '',
  'SchemeType': 'FHRS',
  '_id': ObjectId('6643e433fc3e28490009712e'),
  'geocode': {'latitude': 51.481517791748, 'longitude': 0.0859939977526665},
  'links': [{'href': 'http://api.ratings.food.gov.uk/establishments/695241',
             'rel': 'self'}],
  'meta': {'dataSource': None,
           'extractDate': '0001-01-01T00:00:00',
           'itemCount': 0,
           'pageNumber': 0,
           'pageSize': 0,
           'returncode': None,
           'totalCount': 0,
           'totalPages': 0},
  'scores': {'ConfidenceInManagement': 5, 'Hygiene': 0, 'Structural': 0}},
 {'AddressLine1': '144 - 146 Plumstead High Street',
  'AddressLine2': '',
  'AddressLine3': 'Plumstead',
  'AddressLine4': 'Greenwich',
  'BusinessName': 'Iceland',
  'BusinessType': 'Retailers - supermarkets/hypermarkets',
  'BusinessTypeID': 7840,
  'ChangesByServerID': 0,
  'Distance': 4646.946071297699,
  'FHRSID': 695223,
  'LocalAuthorityBusinessID': 'PI/000178842',
  'LocalAuthorityCode': '511',
  'LocalAuthorityEmailAddress': 'health@royalgreenwich.gov.uk',
  'LocalAuthorityName': 'Greenwich',
  'LocalAuthorityWebSite': 'http://www.royalgreenwich.gov.uk',
  'NewRatingPending': False,
  'Phone': '',
  'PostCode': 'SE18 1JQ',
  'RatingDate': '2019-11-13T00:00:00',
  'RatingKey': 'fhrs_5_en-gb',
  'RatingValue': 5,
  'RightToReply': '',
  'SchemeType': 'FHRS',
  '_id': ObjectId('6643e433fc3e2849000970e9'),
  'geocode': {'latitude': 51.4871482849121, 'longitude': 0.0924199968576431},
  'links': [{'href': 'http://api.ratings.food.gov.uk/establishments/695223',
             'rel': 'self'}],
  'meta': {'dataSource': None,
           'extractDate': '0001-01-01T00:00:00',
           'itemCount': 0,
           'pageNumber': 0,
           'pageSize': 0,
           'returncode': None,
           'totalCount': 0,
           'totalPages': 0},
  'scores': {'ConfidenceInManagement': 5, 'Hygiene': 0, 'Structural': 5}},
 {'AddressLine1': '130 - 132 Plumstead High Street',
  'AddressLine2': '',
  'AddressLine3': 'Plumstead',
  'AddressLine4': 'Greenwich',
  'BusinessName': 'Volunteer',
  'BusinessType': 'Pub/bar/nightclub',
  'BusinessTypeID': 7843,
  'ChangesByServerID': 0,
  'Distance': 4646.965634598608,
  'FHRSID': 694609,
  'LocalAuthorityBusinessID': 'PI/000116619',
  'LocalAuthorityCode': '511',
  'LocalAuthorityEmailAddress': 'health@royalgreenwich.gov.uk',
  'LocalAuthorityName': 'Greenwich',
  'LocalAuthorityWebSite': 'http://www.royalgreenwich.gov.uk',
  'NewRatingPending': False,
  'Phone': '',
  'PostCode': 'SE18 1JQ',
  'RatingDate': '2019-08-05T00:00:00',
  'RatingKey': 'fhrs_5_en-gb',
  'RatingValue': 5,
  'RightToReply': '',
  'SchemeType': 'FHRS',
  '_id': ObjectId('6643e433fc3e28490009711a'),
  'geocode': {'latitude': 51.4873437, 'longitude': 0.09208},
  'links': [{'href': 'http://api.ratings.food.gov.uk/establishments/694609',
             'rel': 'self'}],
  'meta': {'dataSource': None,
           'extractDate': '0001-01-01T00:00:00',
           'itemCount': 0,
           'pageNumber': 0,
           'pageSize': 0,
           'returncode': None,
           'totalCount': 0,
           'totalPages': 0},
  'scores': {'ConfidenceInManagement': 0, 'Hygiene': 0, 'Structural': 0}}]

In [67]:
# Convert result to Pandas DataFrame
top_5_df = pd.json_normalize(results)
top_5_df.head()

,_id,FHRSID,ChangesByServerID,LocalAuthorityBusinessID,BusinessName,BusinessType,BusinessTypeID,AddressLine1,AddressLine2,AddressLine3,...,geocode.longitude,geocode.latitude,meta.dataSource,meta.extractDate,meta.itemCount,meta.returncode,meta.totalCount,meta.totalPages,meta.pageSize,meta.pageNumber
0,6643e433fc3e2849000970f6,1380578,0,14425,Howe and Co Fish and Chips - Van 17,Mobile caterer,7846,Restaurant And Premises 107A Plumstead High St...,,Plumstead,...,0.092537,51.487534,None,0001-01-01T00:00:00,0,None,0,0,0,0
1,6643e433fc3e284900097134,694478,0,PI/000086506,Atlantic Fish Bar,Takeaway/sandwich shop,7844,35 Lakedale Road,,Plumstead,...,0.091216,51.486730,None,0001-01-01T00:00:00,0,None,0,0,0,0
2,6643e433fc3e28490009712e,695241,0,PI/000179088,Plumstead Manor Nursery,Caring Premises,5,Plumstead Manor School Old Mill Road,,Plumstead,...,0.085994,51.481518,None,0001-01-01T00:00:00,0,None,0,0,0,0
3,6643e433fc3e2849000970e9,695223,0,PI/000178842,Iceland,Retailers - supermarkets/hypermarkets,7840,144 - 146 Plumstead High Street,,Plumstead,...,0.092420,51.487148,None,0001-01-01T00:00:00,0,None,0,0,0,0
4,6643e433fc3e28490009711a,694609,0,PI/000116619,Volunteer,Pub/bar/nightclub,7843,130 - 132 Plumstead High Street,,Plumstead,...,0.092080,51.487344,None,0001-01-01T00:00:00,0,None,0,0,0,0

### 4. How many establishments in each Local Authority area have a hygiene score of 0?

In [73]:
# Create a pipeline that:
# 1. Matches establishments with a hygiene score of 0
match_query = {'$match': {'scores.Hygiene': 0}}
# 2. Groups the matches by Local Authority
group_query = {'$group': {'_id': '$LocalAuthorityName', 'count': {'$sum': 1}}}
# 3. Sorts the matches from highest to lowest
sort_values = {'$sort': {'count': -1}}

pipeline = [match_query, group_query, sort_values]
results = list(establishments.aggregate(pipeline))

# Print the number of documents in the result
print(f'Number of documents in the result: {len(results)}')

# Print the first 10 results
pprint(results[0:10])

Number of documents in the result: 55
[{'_id': 'Thanet', 'count': 1130},
 {'_id': 'Greenwich', 'count': 882},
 {'_id': 'Maidstone', 'count': 713},
 {'_id': 'Newham', 'count': 711},
 {'_id': 'Swale', 'count': 686},
 {'_id': 'Chelmsford', 'count': 680},
 {'_id': 'Medway', 'count': 672},
 {'_id': 'Bexley', 'count': 607},
 {'_id': 'Southend-On-Sea', 'count': 586},
 {'_id': 'Tendring', 'count': 542}]

In [77]:
# Convert the result to a Pandas DataFrame
hygiene_zero_df = pd.DataFrame(results)
# Display the number of rows in the DataFrame
print(f'Number of rows in the DataFrame: {hygiene_zero_df["_id"].count()}')

# Display the first 10 rows of the DataFrame
hygiene_zero_df.head(10)

Number of rows in the DataFrame: 55

               _id  count
0           Thanet   1130
1        Greenwich    882
2        Maidstone    713
3           Newham    711
4            Swale    686
5       Chelmsford    680
6           Medway    672
7           Bexley    607
8  Southend-On-Sea    586
9         Tendring    542